server:
  address: 127.0.0.1:443
  maxActiveConn: 100
  enableTls: true

benchmark:
  concurrency: 12
  requestNumPerConcurrency: 1000

cmd:
  commands:
    - benchmark
#    - login
#    - write
#    - read
  username: "1"
