server:
  address: 127.0.0.1:9000
  maxActiveConn: 100

benchmark:
  concurrency: 12
  requestNumPerConcurrency: 100

cmd:
  commands:
    - benchmark
#    - login
#    - write
#    - read
  username: "1"
