server:
  listenAddress: 0.0.0.0:9000
  serverPemFilepath: server.pem
  serverKeyFilepath: server.key
  clientPemFilepath: client.pem

mysql:
  sourceName: root:root@tcp(127.0.0.1:3306)/dora_server
  maxOpenConn: 100
  maxIdleConn: 16
  connMaxLifetime: 100 # second

redis:
  address: 127.0.0.1:6379
  password: "123456"