server:
  listenAddress: 0.0.0.0:443
  serverPemFilepath: server.pem
  serverKeyFilepath: server.key
  clientPemFilepath: client.pem
  enableTls: true

mysql:
  sourceName: root:root@tcp(127.0.0.1:3306)/dora_server
  maxOpenConn: 100
  maxIdleConn: 16
  connMaxLifetime: 100 # second

redis:
  address: 127.0.0.1:6379
  password: "123456"

quotaRepo:
  useMySQL: false
  fixedQuota: 100000

storeRepo:
  useRedis: true