// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

package kv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CODE int32

const (
	CODE_OK                             CODE = 0
	CODE_INCORRECT_USERNAME_OR_PASSWORD CODE = 1000
	CODE_KEY_NOT_EXIST                  CODE = 1001
)

var CODE_name = map[int32]string{
	0:    "OK",
	1000: "INCORRECT_USERNAME_OR_PASSWORD",
	1001: "KEY_NOT_EXIST",
}

var CODE_value = map[string]int32{
	"OK":                             0,
	"INCORRECT_USERNAME_OR_PASSWORD": 1000,
	"KEY_NOT_EXIST":                  1001,
}

func (x CODE) String() string {
	return proto.EnumName(CODE_name, int32(x))
}

func (CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

type Status struct {
	Code                 CODE     `protobuf:"varint,1,opt,name=code,proto3,enum=kv.CODE" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() CODE {
	if m != nil {
		return m.Code
	}
	return CODE_OK
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{1}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRsp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{2}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoginRsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type WriteSecureMessageReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteSecureMessageReq) Reset()         { *m = WriteSecureMessageReq{} }
func (m *WriteSecureMessageReq) String() string { return proto.CompactTextString(m) }
func (*WriteSecureMessageReq) ProtoMessage()    {}
func (*WriteSecureMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{3}
}

func (m *WriteSecureMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteSecureMessageReq.Unmarshal(m, b)
}
func (m *WriteSecureMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteSecureMessageReq.Marshal(b, m, deterministic)
}
func (m *WriteSecureMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteSecureMessageReq.Merge(m, src)
}
func (m *WriteSecureMessageReq) XXX_Size() int {
	return xxx_messageInfo_WriteSecureMessageReq.Size(m)
}
func (m *WriteSecureMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteSecureMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_WriteSecureMessageReq proto.InternalMessageInfo

func (m *WriteSecureMessageReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteSecureMessageReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WriteSecureMessageRsp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteSecureMessageRsp) Reset()         { *m = WriteSecureMessageRsp{} }
func (m *WriteSecureMessageRsp) String() string { return proto.CompactTextString(m) }
func (*WriteSecureMessageRsp) ProtoMessage()    {}
func (*WriteSecureMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{4}
}

func (m *WriteSecureMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteSecureMessageRsp.Unmarshal(m, b)
}
func (m *WriteSecureMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteSecureMessageRsp.Marshal(b, m, deterministic)
}
func (m *WriteSecureMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteSecureMessageRsp.Merge(m, src)
}
func (m *WriteSecureMessageRsp) XXX_Size() int {
	return xxx_messageInfo_WriteSecureMessageRsp.Size(m)
}
func (m *WriteSecureMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteSecureMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WriteSecureMessageRsp proto.InternalMessageInfo

func (m *WriteSecureMessageRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteSecureMessageRsp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ReadSecureMessageReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSecureMessageReq) Reset()         { *m = ReadSecureMessageReq{} }
func (m *ReadSecureMessageReq) String() string { return proto.CompactTextString(m) }
func (*ReadSecureMessageReq) ProtoMessage()    {}
func (*ReadSecureMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{5}
}

func (m *ReadSecureMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSecureMessageReq.Unmarshal(m, b)
}
func (m *ReadSecureMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSecureMessageReq.Marshal(b, m, deterministic)
}
func (m *ReadSecureMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSecureMessageReq.Merge(m, src)
}
func (m *ReadSecureMessageReq) XXX_Size() int {
	return xxx_messageInfo_ReadSecureMessageReq.Size(m)
}
func (m *ReadSecureMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSecureMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSecureMessageReq proto.InternalMessageInfo

func (m *ReadSecureMessageReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ReadSecureMessageRsp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSecureMessageRsp) Reset()         { *m = ReadSecureMessageRsp{} }
func (m *ReadSecureMessageRsp) String() string { return proto.CompactTextString(m) }
func (*ReadSecureMessageRsp) ProtoMessage()    {}
func (*ReadSecureMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{6}
}

func (m *ReadSecureMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSecureMessageRsp.Unmarshal(m, b)
}
func (m *ReadSecureMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSecureMessageRsp.Marshal(b, m, deterministic)
}
func (m *ReadSecureMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSecureMessageRsp.Merge(m, src)
}
func (m *ReadSecureMessageRsp) XXX_Size() int {
	return xxx_messageInfo_ReadSecureMessageRsp.Size(m)
}
func (m *ReadSecureMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSecureMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSecureMessageRsp proto.InternalMessageInfo

func (m *ReadSecureMessageRsp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReadSecureMessageRsp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("kv.CODE", CODE_name, CODE_value)
	proto.RegisterType((*Status)(nil), "kv.Status")
	proto.RegisterType((*LoginReq)(nil), "kv.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "kv.LoginRsp")
	proto.RegisterType((*WriteSecureMessageReq)(nil), "kv.WriteSecureMessageReq")
	proto.RegisterType((*WriteSecureMessageRsp)(nil), "kv.WriteSecureMessageRsp")
	proto.RegisterType((*ReadSecureMessageReq)(nil), "kv.ReadSecureMessageReq")
	proto.RegisterType((*ReadSecureMessageRsp)(nil), "kv.ReadSecureMessageRsp")
}

func init() {
	proto.RegisterFile("kv.proto", fileDescriptor_2216fe83c9c12408)
}

var fileDescriptor_2216fe83c9c12408 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x4e, 0xea, 0x50,
	0x10, 0xc7, 0x6f, 0x7b, 0xa1, 0x94, 0xb9, 0x57, 0x53, 0x27, 0x98, 0xd4, 0xc6, 0x18, 0x52, 0x36,
	0xc4, 0x05, 0x0b, 0x7c, 0x00, 0xe5, 0xa3, 0x21, 0x88, 0x50, 0x72, 0x8a, 0x41, 0xdd, 0x34, 0x15,
	0x4e, 0x08, 0xa9, 0xd0, 0xda, 0xd3, 0xd6, 0xf8, 0x78, 0xbe, 0x8d, 0xbe, 0x85, 0x39, 0xfd, 0x20,
	0x26, 0x40, 0x64, 0xd7, 0x7f, 0x67, 0xf2, 0xeb, 0x6f, 0x66, 0x0a, 0xb2, 0x1b, 0x37, 0xfc, 0xc0,
	0x0b, 0x3d, 0x14, 0xdd, 0x58, 0xbf, 0x01, 0xc9, 0x0a, 0x9d, 0x30, 0x62, 0x78, 0x0e, 0x85, 0x99,
	0x37, 0xa7, 0xaa, 0x50, 0x15, 0xea, 0xc7, 0x4d, 0xb9, 0xe1, 0xc6, 0x8d, 0x8e, 0xd9, 0x35, 0x48,
	0xf2, 0x16, 0x55, 0x28, 0xad, 0x28, 0x63, 0xce, 0x82, 0xaa, 0x62, 0x55, 0xa8, 0x97, 0x49, 0x1e,
	0xf5, 0x36, 0xc8, 0x77, 0xde, 0x62, 0xb9, 0x26, 0xf4, 0x15, 0x35, 0x90, 0x23, 0x46, 0x83, 0xb5,
	0xb3, 0x4a, 0x39, 0x65, 0xb2, 0xc9, 0xbc, 0xe6, 0x3b, 0x8c, 0xbd, 0x79, 0xc1, 0x3c, 0x43, 0x6c,
	0xb2, 0xde, 0xcd, 0x19, 0xcc, 0x47, 0x1d, 0x24, 0x96, 0x18, 0x25, 0x84, 0x7f, 0x4d, 0xe0, 0x26,
	0xa9, 0x23, 0xc9, 0x2a, 0x58, 0x81, 0x62, 0xe8, 0xb9, 0x74, 0x9d, 0x81, 0xd2, 0xa0, 0x5f, 0xc3,
	0xe9, 0x34, 0x58, 0x86, 0xd4, 0xa2, 0xb3, 0x28, 0xa0, 0xc3, 0xd4, 0x8f, 0x6b, 0x29, 0xf0, 0xd7,
	0xa5, 0xef, 0x99, 0x11, 0x7f, 0xe4, 0x80, 0xd8, 0x79, 0x89, 0xf2, 0x61, 0xd2, 0xb0, 0x07, 0xc0,
	0xfc, 0x83, 0x01, 0x75, 0xa8, 0x10, 0xea, 0xcc, 0x7f, 0x17, 0xd0, 0xc7, 0xbb, 0x3a, 0x0f, 0x9f,
	0x7e, 0xfb, 0xdb, 0x97, 0x3d, 0x28, 0xf0, 0x7b, 0xa1, 0x04, 0xa2, 0x39, 0x50, 0xfe, 0x60, 0x0d,
	0x2e, 0xfa, 0xa3, 0x8e, 0x49, 0x88, 0xd1, 0x99, 0xd8, 0xf7, 0x96, 0x41, 0x46, 0xad, 0xa1, 0x61,
	0x9b, 0xc4, 0x1e, 0xb7, 0x2c, 0x6b, 0x6a, 0x92, 0xae, 0xf2, 0x59, 0x42, 0x84, 0xa3, 0x81, 0xf1,
	0x68, 0x8f, 0xcc, 0x89, 0x6d, 0x3c, 0xf4, 0xad, 0x89, 0xf2, 0x55, 0x6a, 0x7e, 0x08, 0x50, 0xb4,
	0x42, 0x2f, 0xa0, 0x58, 0x83, 0x62, 0x72, 0x16, 0xfc, 0xcf, 0x2d, 0xf2, 0x2b, 0x6b, 0x3f, 0x12,
	0xf3, 0xf1, 0x16, 0x70, 0x7b, 0x69, 0x78, 0xc6, 0x7b, 0x76, 0x5e, 0x43, 0xdb, 0x57, 0x62, 0x3e,
	0xf6, 0xe0, 0x64, 0x6b, 0x2b, 0xa8, 0xf2, 0xfe, 0x5d, 0x6b, 0xd5, 0xf6, 0x54, 0x98, 0xdf, 0x2e,
	0x3c, 0x89, 0x6e, 0xfc, 0x2c, 0x25, 0xff, 0xf9, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee,
	0xbd, 0x88, 0x24, 0xf3, 0x02, 0x00, 0x00,
}
