// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv.proto

package kv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WriteSecureMessageReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteSecureMessageReq) Reset()         { *m = WriteSecureMessageReq{} }
func (m *WriteSecureMessageReq) String() string { return proto.CompactTextString(m) }
func (*WriteSecureMessageReq) ProtoMessage()    {}
func (*WriteSecureMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{0}
}

func (m *WriteSecureMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteSecureMessageReq.Unmarshal(m, b)
}
func (m *WriteSecureMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteSecureMessageReq.Marshal(b, m, deterministic)
}
func (m *WriteSecureMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteSecureMessageReq.Merge(m, src)
}
func (m *WriteSecureMessageReq) XXX_Size() int {
	return xxx_messageInfo_WriteSecureMessageReq.Size(m)
}
func (m *WriteSecureMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteSecureMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_WriteSecureMessageReq proto.InternalMessageInfo

func (m *WriteSecureMessageReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *WriteSecureMessageReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WriteSecureMessageRsp struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriteSecureMessageRsp) Reset()         { *m = WriteSecureMessageRsp{} }
func (m *WriteSecureMessageRsp) String() string { return proto.CompactTextString(m) }
func (*WriteSecureMessageRsp) ProtoMessage()    {}
func (*WriteSecureMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{1}
}

func (m *WriteSecureMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriteSecureMessageRsp.Unmarshal(m, b)
}
func (m *WriteSecureMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriteSecureMessageRsp.Marshal(b, m, deterministic)
}
func (m *WriteSecureMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriteSecureMessageRsp.Merge(m, src)
}
func (m *WriteSecureMessageRsp) XXX_Size() int {
	return xxx_messageInfo_WriteSecureMessageRsp.Size(m)
}
func (m *WriteSecureMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WriteSecureMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WriteSecureMessageRsp proto.InternalMessageInfo

func (m *WriteSecureMessageRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReadSecureMessageReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSecureMessageReq) Reset()         { *m = ReadSecureMessageReq{} }
func (m *ReadSecureMessageReq) String() string { return proto.CompactTextString(m) }
func (*ReadSecureMessageReq) ProtoMessage()    {}
func (*ReadSecureMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{2}
}

func (m *ReadSecureMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSecureMessageReq.Unmarshal(m, b)
}
func (m *ReadSecureMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSecureMessageReq.Marshal(b, m, deterministic)
}
func (m *ReadSecureMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSecureMessageReq.Merge(m, src)
}
func (m *ReadSecureMessageReq) XXX_Size() int {
	return xxx_messageInfo_ReadSecureMessageReq.Size(m)
}
func (m *ReadSecureMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSecureMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSecureMessageReq proto.InternalMessageInfo

func (m *ReadSecureMessageReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ReadSecureMessageRsp struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSecureMessageRsp) Reset()         { *m = ReadSecureMessageRsp{} }
func (m *ReadSecureMessageRsp) String() string { return proto.CompactTextString(m) }
func (*ReadSecureMessageRsp) ProtoMessage()    {}
func (*ReadSecureMessageRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2216fe83c9c12408, []int{3}
}

func (m *ReadSecureMessageRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSecureMessageRsp.Unmarshal(m, b)
}
func (m *ReadSecureMessageRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSecureMessageRsp.Marshal(b, m, deterministic)
}
func (m *ReadSecureMessageRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSecureMessageRsp.Merge(m, src)
}
func (m *ReadSecureMessageRsp) XXX_Size() int {
	return xxx_messageInfo_ReadSecureMessageRsp.Size(m)
}
func (m *ReadSecureMessageRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSecureMessageRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSecureMessageRsp proto.InternalMessageInfo

func (m *ReadSecureMessageRsp) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*WriteSecureMessageReq)(nil), "kv.WriteSecureMessageReq")
	proto.RegisterType((*WriteSecureMessageRsp)(nil), "kv.WriteSecureMessageRsp")
	proto.RegisterType((*ReadSecureMessageReq)(nil), "kv.ReadSecureMessageReq")
	proto.RegisterType((*ReadSecureMessageRsp)(nil), "kv.ReadSecureMessageRsp")
}

func init() {
	proto.RegisterFile("kv.proto", fileDescriptor_2216fe83c9c12408)
}

var fileDescriptor_2216fe83c9c12408 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x2e, 0xd3, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xca, 0x2e, 0x53, 0xb2, 0xe7, 0x12, 0x0d, 0x2f, 0xca, 0x2c,
	0x49, 0x0d, 0x4e, 0x4d, 0x2e, 0x2d, 0x4a, 0xf5, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0x4a,
	0x2d, 0x14, 0x12, 0xe0, 0x62, 0xce, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02,
	0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62, 0x10, 0x8e,
	0x92, 0x26, 0x56, 0x03, 0x8a, 0x0b, 0x40, 0x06, 0xe4, 0x16, 0xa7, 0x43, 0x15, 0x83, 0x98, 0x4a,
	0x1a, 0x5c, 0x22, 0x41, 0xa9, 0x89, 0x29, 0x84, 0xad, 0x52, 0xd2, 0xc1, 0xa6, 0xb2, 0xb8, 0x00,
	0xe1, 0x04, 0x46, 0x24, 0x27, 0x18, 0xcd, 0x61, 0xe4, 0x62, 0x0d, 0x2e, 0xc9, 0x2f, 0x4a, 0x15,
	0xf2, 0xe2, 0x12, 0xc2, 0x74, 0x8c, 0x90, 0xa4, 0x5e, 0x76, 0x99, 0x1e, 0x56, 0x5f, 0x4a, 0xe1,
	0x92, 0x2a, 0x2e, 0x10, 0x72, 0xe7, 0x12, 0xc4, 0x70, 0x83, 0x90, 0x04, 0x48, 0x3d, 0x36, 0x4f,
	0x48, 0xe1, 0x90, 0x29, 0x2e, 0x70, 0x62, 0x89, 0x62, 0xca, 0x2e, 0x4b, 0x62, 0x03, 0x87, 0xb9,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xda, 0xdf, 0x90, 0x43, 0x7f, 0x01, 0x00, 0x00,
}
