// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Head struct {
	Version              int32             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SerializeType        string            `protobuf:"bytes,2,opt,name=serialize_type,json=serializeType,proto3" json:"serialize_type,omitempty"`
	Seq                  uint64            `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Method               string            `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Head) Reset()         { *m = Head{} }
func (m *Head) String() string { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()    {}
func (*Head) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Head) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Head.Unmarshal(m, b)
}
func (m *Head) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Head.Marshal(b, m, deterministic)
}
func (m *Head) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Head.Merge(m, src)
}
func (m *Head) XXX_Size() int {
	return xxx_messageInfo_Head.Size(m)
}
func (m *Head) XXX_DiscardUnknown() {
	xxx_messageInfo_Head.DiscardUnknown(m)
}

var xxx_messageInfo_Head proto.InternalMessageInfo

func (m *Head) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Head) GetSerializeType() string {
	if m != nil {
		return m.SerializeType
	}
	return ""
}

func (m *Head) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *Head) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Head) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Pkg struct {
	Head                 *Head    `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pkg) Reset()         { *m = Pkg{} }
func (m *Pkg) String() string { return proto.CompactTextString(m) }
func (*Pkg) ProtoMessage()    {}
func (*Pkg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *Pkg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pkg.Unmarshal(m, b)
}
func (m *Pkg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pkg.Marshal(b, m, deterministic)
}
func (m *Pkg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pkg.Merge(m, src)
}
func (m *Pkg) XXX_Size() int {
	return xxx_messageInfo_Pkg.Size(m)
}
func (m *Pkg) XXX_DiscardUnknown() {
	xxx_messageInfo_Pkg.DiscardUnknown(m)
}

var xxx_messageInfo_Pkg proto.InternalMessageInfo

func (m *Pkg) GetHead() *Head {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *Pkg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Head)(nil), "protocol.Head")
	proto.RegisterMapType((map[string]string)(nil), "protocol.Head.MetaEntry")
	proto.RegisterType((*Pkg)(nil), "protocol.Pkg")
}

func init() {
	proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0)
}

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xc9, 0x36, 0x5d, 0xed, 0xac, 0x16, 0x09, 0x22, 0xc1, 0x53, 0x29, 0x08, 0x3d, 0x48,
	0x0f, 0xeb, 0x41, 0xf1, 0xa8, 0x08, 0x5e, 0x04, 0x09, 0x9e, 0xbc, 0xc8, 0x68, 0x07, 0xb7, 0x6c,
	0x77, 0x53, 0xdb, 0xb8, 0x10, 0x9f, 0xd4, 0xc7, 0x91, 0x8c, 0x36, 0xe0, 0xed, 0xff, 0x26, 0x99,
	0xcc, 0x97, 0x81, 0xbc, 0x1f, 0xac, 0xb3, 0x6f, 0xb6, 0xab, 0x39, 0xa8, 0xfd, 0x89, 0xcb, 0x6f,
	0x01, 0xf2, 0x9e, 0xb0, 0x51, 0x1a, 0xf6, 0x76, 0x34, 0x8c, 0xad, 0xdd, 0x6a, 0x51, 0x88, 0x2a,
	0x35, 0x13, 0xaa, 0x33, 0xc8, 0x47, 0x1a, 0x5a, 0xec, 0xda, 0x2f, 0x7a, 0x71, 0xbe, 0x27, 0x3d,
	0x2b, 0x44, 0x95, 0x99, 0xc3, 0x58, 0x7d, 0xf2, 0x3d, 0xa9, 0x23, 0x48, 0x46, 0xfa, 0xd0, 0x49,
	0x21, 0x2a, 0x69, 0x42, 0x54, 0x27, 0x30, 0xdf, 0x90, 0x5b, 0xd9, 0x46, 0x4b, 0x6e, 0xf8, 0x23,
	0x75, 0x0e, 0x72, 0x43, 0x0e, 0x75, 0x5a, 0x24, 0xd5, 0x62, 0xa9, 0xeb, 0x28, 0x17, 0x44, 0xea,
	0x07, 0x72, 0x78, 0xb7, 0x75, 0x83, 0x37, 0x7c, 0xeb, 0xf4, 0x12, 0xb2, 0x58, 0x0a, 0x43, 0xd6,
	0xe4, 0xd9, 0x30, 0x33, 0x21, 0xaa, 0x63, 0x48, 0x77, 0xd8, 0x7d, 0x4e, 0x52, 0xbf, 0x70, 0x3d,
	0xbb, 0x12, 0xe5, 0x2d, 0x24, 0x8f, 0xeb, 0x77, 0x55, 0x82, 0x5c, 0x11, 0x36, 0xdc, 0xb3, 0x58,
	0xe6, 0xff, 0xa7, 0x19, 0x3e, 0x0b, 0x9f, 0xef, 0xd1, 0x77, 0x16, 0x1b, 0x7e, 0xe6, 0xc0, 0x4c,
	0x78, 0x03, 0xcf, 0x71, 0x57, 0xaf, 0x73, 0x4e, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83,
	0xd5, 0x4b, 0x34, 0x4e, 0x01, 0x00, 0x00,
}
